language: ruby


rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6

matrix:
  include:
    - rvm: jruby-head
      jdk: oraclejdk11


notifications:
  email:
    on_success: never
  slack:
    secure: AMXcZSwIL8SRZQ+opSFrlvNKoUXv1rZkWDgorBmz+BEHwGKWgVzYcZ4GwD5p6Z5uNdtvl9FZz6oLvvAcbW6CblbAPM+f2qLVDlZ/sazpOK8l6QIo7X86U3SuwJicY2CbbKvqN/A3u23Bbvf5u4djvm5oc73qASZY/RJHxm2xcmD57+z6hY12AvWtLJN95BsjVZ9RHXy8/qkJehqGnzSi9VGojNmd0voU9UrxJU0xS10kBA7dQFCCf+NZv9utguyFfAATpa9JTlD1a8QiB2fzvdPkBym1bnqr3nQPk5rNbgiFHf14OIlq7C2jwaNNoB1dDpkT/Vfvmn5EHzBDZQ30PrVpq9uNgQg45pOIMXp9ZLY0zYi/Gzk5tF/lTKUxk5evJ2+2Dtmzv4mzbk98pvGrA+MIkSXuYy6GHZuXanb3OQ5y42dSYVdy1c+WHdbYx1LOJSEGtALr9ADyjDu9KAu2eJMnmGQ14cJarl/33BF4UzCRKpPxV5CwOqI82+fK9pNiW0CLijfxpkFr9aaxViVsf43r5Ag12Jqme18IWCGJ1P5sMEo6bz/Gp4BuVMXQtYExorK+fWkrm1Wus6HGINlRonUswJ9LJ995M384j6KyP1121MJuiPAc1AdNqS1C992j/cDoUDlxsxW9HTX15nGoM712w00wNrj/vdQt0TlmENo=

sudo: false

env:
  global:
    # If changing this number, please also change it in `test/test_helper.rb`.
    - TELNYX_MOCK_VERSION=0.7.1

cache:
  directories:
    - telnyx-mock

before_install:
  # Install bundler 1.x, because we need to support Ruby 2.1 for now
  - gem install bundler -v "~> 1.0"
  # Unpack and start telnyx-mock so that the test suite can talk to it
  - |
    if [ ! -d "telnyx-mock/telnyx-mock_${TELNYX_MOCK_VERSION}" ]; then
      mkdir -p telnyx-mock/${TELNYX_MOCK_VERSION}/
      curl -L "https://github.com/team-telnyx/telnyx-mock/releases/download/v${TELNYX_MOCK_VERSION}/telnyx-mock_${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz" -o "telnyx-mock/telnyx-mock_${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "telnyx-mock/telnyx-mock_${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz" -C "telnyx-mock/${TELNYX_MOCK_VERSION}/"
    fi
  - |
    telnyx-mock/${TELNYX_MOCK_VERSION}/telnyx-mock > /dev/null &
    TELNYX_MOCK_PID=$!
  - export PATH="${PATH}:${PWD}/telnyx-mock/${TELNYX_MOCK_VERSION}"

script:
  - bundle exec rake
